config/routes.rb
Rails.application.routes.draw do

  get 'posts/show'

  get 'users/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  get "search", to: "home#index"
  get 'user' => 'users/index'
  get 'home/index'
  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	@@client = Tumblr::Client.new :consumer_key => 'azMJTMHgd2spw9Jbw3LZNe9ZAH4L3zlBDzgemPYZCoqNK0v6aX'
	@@timestamp = 0
	@@tag = 'art'
  def index
  	if params[:search] == nil
  		@@tag = 'art'
  	else
  		@@tag = params[:search]
  	end
  	if @@timestamp == 0
  		result = @@client.tagged @@tag
  	else
  		result = @@client.tagged @@tag, :before => @@timestamp
  	end
  	posts = []
  	for post in result
  		if post["type"] == "photo"
  			posts.push(post["photos"])
  			if user_signed_in?
  				new_post = Post.new(:blog_name => post["blog_name"], :post_url => post["post_url"], :date => post["date"], :tags => "", :user => current_user)
  				new_post.save
  			end
  			if @@timestamp > post["timestamp"] or @@timestamp == 0
  				@@timestamp = post["timestamp"]
  			end
  		end
  	end
  	
  	p @@timestamp
  	@images = []
  	for photoset in posts
  		for photo in photoset
  			@images.push(photo["original_size"])
  		end
  	end
  	return @images
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
  	@posts = Post.where(user: current_user)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to users_path
  	else
  		render 'new'
  	end
  end

  def index
  	@users = User.all
  end

  def show
  	@posts = Post.where(belongs_to: current_user)
  end

  private

  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!-- include jQuery library -->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<!-- include Cycle plugin -->
<script type="text/javascript" src="http://malsup.github.com/jquery.cycle.all.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('.slideshow').cycle({
		fx: 'fade',
		speed: 'fast',
		timeout: '1000',
		nowrap: 'true',
		end: function () {
			$.ajax(location.reload())
		}
	});
});
</script>

<body style="background-color: black">
<div id="tumblr" class="container" style="background-color: black" >
	<div class="slideshow">
	<% for image in @images do %>
		<% if image["height"] > 650 %>
			<% new_width = image["width"] - (image["width"] * (image["height"] - 650)/image["height"]) %>
			<div><img class="img-responsive" style="margin: auto" width=<%=new_width%> src=<%= image['url'] %>></div>
		<% else %>
			<div><img class="img-responsive" style="margin: auto" src=<%= image['url'] %>></div>
		<% end %>
	<% end %>
	</div>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlashMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</head>
<body>
<nav class="navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/home/index">
      	FlashMe
      </a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= form_tag search_path, method: :get do%>
        <%= text_field_tag :search %>
        <%= submit_tag "Search"%> <% end %>
      </li>
      <% if user_signed_in? %>
    	<li><%= link_to(current_user.first_name, posts_show_path) %></li>
    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </li>
		<% else %>
		<li><%= link_to('Login', new_user_session_path) %> </li>
		<li> <%= link_to "Sign Up", new_user_registration_path %> </li>
		<% end %>
	</ul>
  </div>
</nav>
<%= yield %>

</body>
</html>

app/views/posts/show.html.erb
<h1><%=current_user.first_name%> <%=current_user.last_name%>'s History</h1>
<div class="container">
	<table>
		<tr>
			<td>Blog Name</td>
			<td>Post URL</td>
			<td>Date</td>
		</tr>
		<% @posts.each do |post| %>
		<tr>
			<td> <a href=<%="//" + post.blog_name + ".tumblr.com"%>><%=post.blog_name%></a> </td>
			<td> <a href=<%="//" + post.post_url %>><%=post.post_url%></a> </td>
			<td> <%=post.date %> </td>
		</tr>
		<% end %>
	</table>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<table>
	<tr>
		<td>Name</td>
		<td>Email</td>
		<td>Password</td>
	</tr>
	<% @users.each do |user| %>
	<tr>
		<td><%= user.name %></td>
		<td><%= user.email %></td>
		<td><%= user.password %></td>
	</tr>
	<% end %>
</table>

app/views/users/new.html.erb
<h1>Add New User</h1>
<%= form_for(@user) do |f| %>
	<div class="field">
		<p>Name</p>
		<%= f.text_field :name%>
	</div>
	<div class="field">
		<p>Email</p>
		<%= f.text_field :email%>
	</div>
	<div class="field">
		<p>Password</p>
		<%= f.text_field :password%>
	</div>
	<div class="actions">
		<%= f.submit%>
	</div>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>